{
 "title": "Quilibrium Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": "label_values(origin_prometheus)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
   },
   { "name": "quil_price", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Live peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "root_is_not_array": true
     },
     "pagination_mode": "none",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json",
     "url": "https://dashboard-api.quilibrium.com/live-peers",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api.livecoinwatch.com/coins/single",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n    \"currency\": \"USD\",\n    \"code\": \"WQUIL\",\n    \"meta\": true\n  }",
      "headers": [
       {
        "key": "x-api-key",
        "value": "c1a3670b-fa4d-438f-8a93-19a204f10c82"
       }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Balance (Q)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(quilibrium_unclaimed_balance{}[24h]) * 60 * 60 * 24)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(quilibrium_unclaimed_balance{}[24h]) * 60 * 60 * 24 * 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "My nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) ({__name__=~\".+\",job=\"integrations/quilibrium_exporter\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance ($)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(quilibrium_unclaimed_balance{}[24h]) * 60 * 60 * 24) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(quilibrium_unclaimed_balance{}[24h]) * 60 * 60 * 24 * 30) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Quilibrium",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "last_over_time(quilibrium_unclaimed_balance [1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(quilibrium_max_frame [1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(quilibrium_unclaimed_balance{}[24h]) * 60 * 60 * 24",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(quilibrium_unclaimed_balance{}[24h]) * 60 * 60 * 24 * 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server resource overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"integrations/quilibrium_exporter\"})by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_uname_info{job=\"integrations/quilibrium_exporter\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"integrations/quilibrium_exporter\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"integrations/quilibrium_exporter\", mode='system'}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=\"integrations/quilibrium_exporter\", mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"integrations/quilibrium_exporter\"} / (node_memory_MemTotal_bytes{job=\"integrations/quilibrium_exporter\"})))* 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=\"integrations/quilibrium_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"integrations/quilibrium_exporter\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=\"integrations/quilibrium_exporter\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=\"integrations/quilibrium_exporter\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=\"integrations/quilibrium_exporter\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"integrations/quilibrium_exporter\",}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"integrations/quilibrium_exporter\",}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node details【$show_hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Balance (Q)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance{hostname=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(quilibrium_unclaimed_balance{hostname=\"$node\"}[24h]) * 60 * 60 * 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / month",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(quilibrium_unclaimed_balance{hostname=\"$node\"}[24h]) * 60 * 60 * 24 * 30 * $quil_price ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 11, "x": 12, "y": 19 } },
  {
   "title": "Balance ($)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quilibrium_unclaimed_balance{hostname=\"$node\"}) * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated $ / day",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(quilibrium_unclaimed_balance{hostname=\"$node\"}[24h]) * 60 * 60 * 24 * $quil_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Q / month",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(quilibrium_unclaimed_balance{hostname=\"$node\"}[24h]) * 60 * 60 * 24 * 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "quilibrium_peer_store_count{hostname=\"$node\"}",
     "legendFormat": "peer store"
    },
    {
     "expr": "quilibrium_network_peer_count{hostname=\"$node\"}",
     "legendFormat": "network peers"
    }
   ]
  },
  {
   "title": "Peers sync per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (peer_id)( count_over_time({unit=\"quilibrium.service\", hostname=\"$node\"} |= `syncing target` [1m]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Internet traffic per hour $device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}